name: antlr4dart
version: 0.7.0
author: Tiago Mazzutti <tiagomzt@gmail.com>
description: ANTLR4 runtime library for Dart.
homepage: https://github.com/tiagomazzutti/antlr4dart-runtime.git
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  bit_array: ^2.0.0
  collection: ^1.14.12
